### PR TITLE
Fix #56

### LINKED ISSUE #56: Scala 3: case objects with `override val toString` get a duplicate definition
```scala

case object CaseObjectWithToString {
  override val toString: String = "example"
}
```

```scala
[error] -- [E120] Naming Error: /Users/jkoslowski/IdeaProjects/better-tostring/tests/src/test/scala/Demo.scala:86:12 
[error] 86 |case object CaseObjectWithToString {
[error]    |            ^
[error]    |Double definition:
[error]    |override def toString(): String in object CaseObjectWithToString at line 87 and
[error]    |override def toString(): String in object CaseObjectWithToString
```

### PR DESCRIPTION
**Pull request by kubukoz**
- Fixes #56 by including vals in our search for existing `toString`s
- removes `$` and `()` from the toStrings of case objects in Scala 3 (I think it wasn't an issue in Scala 2 because we never touch case objects in these versions)
- Adds some tests that should help when working on #34 and #60, as well as current enum subclass behavior

### CODE REVIEW

File: plugin/src/main/scala-2/Scala2CompilerApi.scala [hunk 1]
```diff
@@ -49,11 +49,13 @@ object Scala2CompilerApi {
       def addMethod(clazz: Clazz, method: Method): Clazz =
         clazz.copy(impl = clazz.impl.copy(body = clazz.impl.body :+ method))
 
-      def methodNames(clazz: Clazz): List[String] = clazz.impl.body.collect { case d: DefDef =>
-        d.name.toString
+      def methodNames(clazz: Clazz): List[String] = clazz.impl.body.collect {
+        case d: DefDef => d.name.toString
+        case d: ValDef => d.name.toString
```
Comment (kubukoz) [inline plugin/src/main/scala-2/Scala2CompilerApi.scala:54]: This was added to support `override val toString` in both Scala versions. A better name for `methodNames` would be welcome, although `memberNames` would miss `var` (which isn't a suitable implementation for `toString`)

File: plugin/src/main/scala-2/Scala2CompilerApi.scala [hunk 2]
```diff
@@ -49,11 +49,13 @@ object Scala2CompilerApi {
...
       }
 
       def isCaseClass(clazz: Clazz): Boolean = clazz.mods.hasFlag(Flags.CASE)
+      def isObject(clazz: Clazz): Boolean = clazz.mods.hasFlag(Flags.MODULE)
```
Comment (kubukoz) [inline plugin/src/main/scala-2/Scala2CompilerApi.scala:58]: This is added to skip `()` from case objects.

File: plugin/src/main/scala-3/Scala3CompilerApi.scala [hunk 3]
```diff
@@ -34,7 +37,8 @@ object Scala3CompilerApi:
         case v: ValDef if v.mods.is(CaseAccessor) => v
       }
 
-    def className(clazz: Clazz): String = clazz.clazz.name.toString
+    def className(clazz: Clazz): String =
+      clazz.clazz.originalName.toString
```
Comment (kubukoz) [inline plugin/src/main/scala-3/Scala3CompilerApi.scala:41]: `originalName` lets us avoid the `$` in case objects.

File: plugin/src/main/scala-3/Scala3CompilerApi.scala [hunk 4]
```diff
@@ -68,10 +72,17 @@ object Scala3CompilerApi:
     def addMethod(clazz: Clazz, method: Method): Clazz =
       clazz.mapTemplate(t => cpy.Template(t)(body = t.body :+ method))
 
-    def methodNames(clazz: Clazz): List[String] = clazz.t.body.collect { case d: DefDef =>
-      d.name.toString
-    }
+    // note: also returns vals because why not
+    def methodNames(clazz: Clazz): List[String] =
+      clazz.t.body.collect { case d: (DefDef | ValDef) =>
```
Comment (mrobakowski) [inline plugin/src/main/scala-3/Scala3CompilerApi.scala:77]: You can do that in Scala 3??? pog

**Review by mrobakowski — APPROVED** [review]
LGTM

File: plugin/src/main/scala-3/Scala3CompilerApi.scala (hunk 4 above)
Comment (kubukoz) [reply plugin/src/main/scala-3/Scala3CompilerApi.scala:77]: Apparently :D
